version: 3

images:
  base_image:
    name: registry.access.redhat.com/ubi9/python-312:latest

dependencies:
  python_interpreter:
    python_path: /usr/bin/python3
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  python:
    - ansible-lint
  galaxy:
    collections:
      - name: community.general
      - name: community.crypto
      - name: ansible.posix
